services:
  web:
    build: .
    command: python bjoern.py
    ports:
      - "127.0.0.1:8023:5000"
    environment:
      FLASK_DEBUG: ${FLASK_DEBUG:-1}
      HOST: 0.0.0.0
      PORT: 5000
    env_file:
      - .env
    restart: always
    volumes:
      - ./images:/app/images
      - ./videos:/app/videos
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"

  postgres:
    image: postgres:15
    container_name: image_postgres
    restart: always
    environment:
      POSTGRES_USER: subpolare
      POSTGRES_PASSWORD: subpolare
      POSTGRES_DB: i_subpolare_ru
    volumes:
      - /home/subpolare/pgdata_i_subpolare_ru:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-isubpolareru}"]
      interval: 5s
      timeout: 5s
      retries: 5